name: Deploy website and push code

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # container:
      #image
    steps:
      - uses: actions/checkout@v3
      # with:
        # 
      - run: npm ci
      - run: npm test
      - run: deploy
      # - run: git add .
      # - run: git commit -m "Automated deployment + code push"
      # - run: git push